### ISSUE TITLE
Fortinet False Positive Form

### ISSUE THREAD

**Issue by bitKrakenCode** [yaronelh/False-Positive-Center#33]
I found the false positve form for urls by FortiGuard / Fortinet that is a bit simpler as the existing one and only for classification.
If you want to add this too: https://www.fortiguard.com/faq/wfratingsubmit

**Comment by yaronelh** [comment]
Thanks for sending this, but it seems to be for web URLs not software.
This repository is specifically for false-positive around software

Cheers

**Comment by bitKrakenCode** [comment]
whoopsie daisy. your list was very helpfull in my url reports anyway ;)
but I will close this then.
thanks for the fast reply! cheers
