### ISSUE TITLE
Add Contact Info / URLs for Safe Browsing False Positives

### ISSUE THREAD

**Issue by rcmaehl** [yaronelh/False-Positive-Center#35]
While this list works for Executable false positives, there also exists false positives for web browsing.  Per VirusTotal, the following services provide Safe Browsing Services:

Avira
Abusix
Acronis
ADMINUSLabs
AICC (MONITORAPP)
AlienVault
alphaMountain.ai
Antiy-AVL
Artists Against 419
AutoShun
BADWARE.INFO
benkow.cc
Bfore.Ai PreCrime
BitDefender
BlockList
Blueliv
Certego
Chong Lua Dao
CINS Army
CMC Threat Intelligence
Comodo Valkyrie Verdict
CRDF
Cyan
CyberCrime
Cyble
CyRadar
desenmascara.me
DNS8
Dr.Web
EmergingThreats
Emsisoft
ESET
ESTsecurity
Feodo Tracker
Forcepoint ThreatSeeker
Fortinet
G-Data
GreenSnow
Google Safebrowsing
Heimdal Security
Hoplite Industries
IPsum
Juniper Networks
K7AntiVirus
Kaspersky
Lionic
Lumu
MalBeacon
MalSilo
Malwared
MalwarePatrol
malwares.com URL checker
Netcraft
Nucleon
OpenPhish
Phishing Database
PhishLabs
Phishtank
PREBYTES
Quick Heal
Quttera
Rising
SafeToOpen
Sangfor
Scantitan
SCUMWARE.org
Seclookup
SecureBrain
securolytics
Snort IP sample list
Sophos
Spam404
StopForumSpam
Sucuri SiteCheck
ThreatHive
Threatsourcing
Trustwave
URLhaus
URLQuery
Viettel Threat Intelligence
ViriBack
Virusdie External Site Scan
VX Vault
Web Security Guard
Webroot
Yandex Safebrowsing
ZeroCERT
0xSI_f33d

**Comment by yaronelh** [comment]
Hi @rcmaehl

Sorry about the delay I wasn't in front of a computer for a few days, this list focuses strictly on software false-positives
But it could definitely easily be forked If you want to add Website scanning as well

All The Best
Yaron Elharar

**Comment by rcmaehl** [comment]
> Hi @rcmaehl
> 
> Sorry about the delay I wasn't in front of a computer for a few days, this list focuses strictly on software false-positives But it could definitely easily be forked If you want to add Website scanning as well
> 
> All The Best Yaron Elharar

Will do!
