### ISSUE TITLE
MaxSecure and Malwarebytes new contact info

### ISSUE THREAD

**Issue by Dragodraki** [yaronelh/False-Positive-Center#36]
A assume MaxSecure isn't longer reachable under tech@maxpcsecure.com. I never get answer when using it. An working mail adress is info@maxpcsecure.com.

Malwarebytes is almost impossible to contact via Forum - additionally the necessary registration is a nightmare in the first place. But you can yontact the support on this website and reach files as attachment too:
https://support.malwarebytes.com/hc/en-us/requests/new

Maybe you'd like to update your list with these improvements.

**Comment by yaronelh** [comment]
Hi Dragodraki, sorry for the delayed response
I've updated the table 👍
