### ISSUE TITLE
Great job (no irony)!

### ISSUE THREAD

**Issue by Dragodraki** [yaronelh/False-Positive-Center#37]
Thank you very much for keeping this list up to date.
It helps persons like me dealing with false positives a lot, because most AV vendors don't provide their contact for free / unregistered users by their own.
:)
So, thanks again - and sorry for abusing this method a little bit to contact you.
(Of course you can close this 'issue' tight away)

**Comment by yaronelh** [comment]
You're welcome 👍, and if you ever encounter something inaccurate just send me a message
