### ISSUE TITLE
Cynet is not possible to contact

### ISSUE THREAD

**Issue by capashaa** [yaronelh/False-Positive-Center#41]
Hey and thanks for your awesome list. I have tried to contact Cynet, but get redirected to their portal when I have submitted false positives. You need to be a an existing consumer to be able to login to their community portal.

This is the portal that they redirect me to. And I can't do anything https://cynet.force.com/Community/s/login/.

**Comment by yaronelh** [comment]
I'm not sure I understand, is the Cynet email in the table no longer accurate?

**Comment by capashaa** [comment]
Sorry. But the email for Cynet is correct. I could submit false positives. The only message I get back is that I need to sign in to their portal and that my message is put there. And the only way to sign in to their portal is, if you are a consumer. So I'm kinda frustrated over this, that I cant write to them but they can't write to me.

**Comment by yaronelh** [comment]
Interesting, did you try contacting their support?

**Comment by capashaa** [comment]
I didn't contact their support. But I will do that when I have more time.

**Comment by yaronelh** [comment]
Let me know what you find out, as far as I currently know it's accurate but reopened if you find something different through your communication with them
