### ISSUE TITLE
Remove save@sangfor.com.cn

### ISSUE THREAD

**Issue by dragokas** [yaronelh/False-Positive-Center#43]
![image](https://github.com/yaronelh/False-Positive-Center/assets/19956568/ff7f11ac-2926-4dbd-ae66-1dc1f96d30db)

**Comment by dragokas** [comment]
@yaronelh just in case, we also have a similar own database, which we're updating periodically: https://www.safezone.cc/threads/kuda-soobschit-o-lozhnom-srabatyvanii-antivirusa.23501/
Well, I'm a bit lazy to make a pull request for such a large list. Just inform you where you could sometimes look for the fresh info.
Regards.

**Comment by yaronelh** [comment]
Finally had some time to take a look, They seem to have a pdf guide going through the steps of reporting false positives i've added the PDF to the list, removed everything else.
