### ISSUE TITLE
Deep Instinct

### ISSUE THREAD

**Issue by vshoolgin** [yaronelh/False-Positive-Center#47]
[yaronelh](https://github.com/yaronelh/False-Positive-Center/commits?author=yaronelh), Thanx for good project, its very helpful for me and a lot of developers too!
I want to add Deep Instinct contacts, they answered to me after one day.

Deep Instinct - info@deepinstinct.com

**Comment by yaronelh** [comment]
Thanks for the compliment👍, Added.
