### ISSUE TITLE
Certego

### ISSUE THREAD

**Issue by Absenti** [yaronelh/False-Positive-Center#51]
hello, for certego the email is fp@certego.net

**Comment by yaronelh** [comment]
Thanks for bringing it up, How do you know that that's the email? couldn't find any information about it

**Comment by Absenti** [comment]
Hello
You can find the email here, at the bottom of the website page : 
https://www.certego.net/services/cyber-threat-intelligence/

**Comment by yaronelh** [comment]
Thanks for the additional information it's very interesting, The way they phrase the sentence "Do you want to report a False Positive Detection on VirusTotal? Please contact us:" 

Seems like there talking about any detection by any vendor which is strange, but awesome if that's what they meant
In any case adding it, Cheers
