### ISSUE TITLE
Gridinsoft new url

### ISSUE THREAD

**Issue by fxdeniz** [yaronelh/False-Positive-Center#52]
Hi @yaronelh, thanks for the project.

Gridinsoft has new url for sample submission: https://gridinsoft.com/incorrect-detection

Old url: https://anti-malware.gridinsoft.com/false-detect/
redirects to new one.

It looks like change happened recently, in the future, redirection may not work.

**Comment by yaronelh** [comment]
thanks for letting me know I have updated the information 👍
