### ISSUE TITLE
Malwarebytes close tickets when no subscription

### ISSUE THREAD

**Issue by Dragodraki** [yaronelh/False-Positive-Center#70]
Your link https://support.malwarebytes.com/hc/en-us/requests/new seems to be for paid users only. If free version or VirusTotal detects software and I write a ticket, their answer is that they did not found any related subscription with my mail adress and that the ticket is closed now.

Is there another way to contact them for free when it comes to problems with free Malwarebytes or VirusTotal database false positives?

**Comment by isaak654** [comment]
For false positives: https://support.malwarebytes.com/hc/en-us/articles/360038524154

**Comment by yaronelh** [comment]
Updated the list  
Thanks @Dragodraki , @isaak654
