### ISSUE TITLE
no way to submit false positive with Skyhigh (SWG)

### ISSUE THREAD

**Issue by kotenok2000** [yaronelh/False-Positive-Center#77]

**Comment by yaronelh** [comment]
Did you figure out how to contact them?

**Comment by kotenok2000** [comment]
Only this: https://success.skyhighsecurity.com/Skyhigh_Secure_Web_Gateway_(On_Prem)/Anti-malware_Filtering/How_to_submit_false_positive%2F%2Fnegative_samples_for_review
But i can't send a customer support service request, because i am not a customer.

**Comment by yaronelh** [comment]
What about following the process here? (Process Avira)

https://success.skyhighsecurity.com/Skyhigh_Secure_Web_Gateway_%28On_Prem%29/Anti-malware_Filtering/How_to_submit_false_positive%2F%2Fnegative_samples_for_review

**Comment by yaronelh** [comment]
You can also use this contact email [virus_research_gateway@avertlabs.com](mailto:virus_research_gateway@avertlabs.com) 
just indicate that it's for Skyhigh (SWG) detection
