### ISSUE TITLE
Rising antivirus doesn't analyze reported files

### ISSUE THREAD

**Issue by kotenok2000** [yaronelh/False-Positive-Center#82]
When i reported false positive using http://mailcenter.rising.com.cn/filecheck_en/
 in 2021 they gave me a tracking number.
I checked today and they still didn't do anything with this file.
![image](https://github.com/yaronelh/False-Positive-Center/assets/8822292/dfa8dab1-3b8a-4934-af25-4001b81cac60)

**Comment by yaronelh** [comment]
Did you find any other way to contact them? As far as I know, that's the only one

**Comment by kotenok2000** [comment]
No.

**Comment by xTararAisx** [comment]
It's also limited to 30MB, why would virustotal add such a outdated vendor to their ddbb?
