### ISSUE TITLE
Kaspersky false positive reporting not working

### ISSUE THREAD

**Issue by nfedera** [yaronelh/False-Positive-Center#84]
Quoting: https://forum.kaspersky.com/topic/kaspersky-how-to-report-false-positive-22328/  (January 1, 2022)

> If you suspect a false positive:
>
> Check the file or the website using [OpenTip](https://opentip.kaspersky.com/). 
> If you do not agree with the results, send the object for further analysis to Kaspersky specialists.
> To do this, click **Submit to reanalyze** on the results page.

This is also documented here:
https://support.kaspersky.com/common/error/other/1870

Well, either I'm blind or there is noch such "_submit to reanalyze_" option/button/link whatsoever.

Quoting the other documented way of false positive reporting from March 21, 2024 in a document called [What to do if a Kaspersky application blocks my website or application](https://support.kaspersky.com/common/error/other/15332) :

> contact:
> [Kaspersky technical support](https://support.kaspersky.com/b2b#contacts)
>
> In your request, provide the following information:
>
>- The name and version of your Kaspersky application
>- Request type: Malware
>- Request topic: False positive
>- The operating system version
>- The sample file or full link to the object on the website that was detected as a false positive.
>- Add the file to a password-protected archive. Set the password infected and specify it in your request.
>- The database update date of the Kaspersky application

However, that form does not work as described, there is no upload option at all. After selecting the "_false positive_" option  you are merely presented with an "_other customers find this information helpful_" link to the following article https://support.kaspersky.com/us/1870 that suggests requesting reanalysis via opentip - which does not work.

And below there is a "_Did not find your answer? Contact Customer Service_" link that opens a generic error reporting form that only  allows to attach files up to 10MB.

I think I have seen / used the reanalyze option in opentip 1 or 2 years ago and hope that this is only a technical issue.

Can somebody maybe confirm that it is indeed missing ?

**Comment by yaronelh** [comment]
It's this one. It doesn't appear for you?
![image](https://github.com/yaronelh/False-Positive-Center/assets/7690499/4753eaa7-d8e4-4d1f-9f1e-0f0b9d5abf44)

Regarding the other method, that also works. All you need to do is click that button underneath this one (I already clicked it, It said something like continue to contact support) It opens the rest of the form 

![image](https://github.com/yaronelh/False-Positive-Center/assets/7690499/051fafa4-f281-4657-ae58-9839c69198b4)

**Comment by yaronelh** [comment]
These are the selections 

![image](https://github.com/yaronelh/False-Positive-Center/assets/7690499/afdfde20-c62f-4ee9-95d4-232527631cf5)

**Comment by nfedera** [comment]
Interesting, neither of those appear for my last reports/uploads.
However, I've managed to fix the false positive via direct email communication.
