### ISSUE TITLE
No way to submit FP to ViRobot

### ISSUE THREAD

**Issue by kotenok2000** [yaronelh/False-Positive-Center#85]

**Comment by kotenok2000** [comment]
It seems Hauri still uses ViRobot name on virustotal.

**Comment by yaronelh** [comment]
Did you find a way to report to them?

**Comment by kotenok2000** [comment]
I found only reference to virobot on https://company.hauri.net/product/anti_virus.html
There is a Hauri email on the list.

**Comment by yaronelh** [comment]
did you get a response?
(The page for me doesn't load)

**Comment by kotenok2000** [comment]
works for me
![image](https://github.com/yaronelh/False-Positive-Center/assets/8822292/efc65154-7924-4acc-a3d9-7924d6ef4a83)

**Comment by yaronelh** [comment]
As for emails I could only find this one, as a way to report to them report to them [viruslab@hauri.co.kr](mailto:viruslab@hauri.co.kr)

**Comment by yaronelh** [comment]
I'm closing it for now. It seems that the email is is the only way to report to them unless something else comes up 🤷
