### ISSUE TITLE
Outdated emails

### ISSUE THREAD

**Issue by kotenok2000** [yaronelh/False-Positive-Center#86]
I got `550 5.1.1 ... User unknown`  for bav@baidu.com and  `550 5.4.1 Recipient address rejected: Access denied. [SG1PEPF000082E7.apcprd02.prod.outlook.com 2024-06-30T12:02:10.487Z 08DC98AB4188B69B]`  for  vulambang@cmcinfosec.com

**Comment by yaronelh** [comment]
Searching around the web I found this information, There seem to be a way to submit for software 

**Baidu Antivirus false positive submissions (seems to not work anymore)**
http://anquan.baidu.com/shadu/shadu_form.html
http://anquan.baidu.com/shadu/sample/1

**It seems that there was also a Baidu Software Security Certification Platform (This link also doesn't work)**
http://open.rj.baidu.com/

**Reporting Baidu false positives for websites, does exist and at the time of writing works at these links** 
[bsb.baidu.com/appeal2](bsb.baidu.com/appeal2)
[bsb.baidu.com/appeal](bsb.baidu.com/appeal)
