### ISSUE TITLE
There is another list of false positive contacts at https://docs.virustotal.com/docs/false-positive-contacts

### ISSUE THREAD

**Issue by kotenok2000** [yaronelh/False-Positive-Center#88]
It was updated 29 days ago.

**Comment by yaronelh** [comment]
Yes 👍, there is a link in the git to this page 

![image](https://github.com/user-attachments/assets/2dbbbbc0-3da7-4de0-a68c-ac920eeab6e9)

**Comment by kotenok2000** [comment]
I have found google vt email there.
it is [google-at-virustotal@google.com](mailto:google-at-virustotal@google.com)

**Comment by yaronelh** [comment]
added 👍
